#! /bin/sh

# Script executed at boot time

# Mount proc and sys (mount -t <type> <device> <mount_point>)
mount none /proc -t proc
mount none /sys  -t sysfs

# Mount devpts for pseudo-terminals
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Remount / in read-write mode
mount / -o remount,rw

/sbin/mdev -s
echo /sbin/mdev > /proc/sys/kernel/hotplug

# Configure the keyboard in AZERTY
loadkmap < /etc/azerty.kmap

# Start HTTP server
httpd -h /var/www/html

# Start SSH server
dropbear -ER

# Retrieve the IP address with DHCP
sleep 5 # AFTER A 5 SECOND DELAY (TO ALLOW THE NETWORK TO COME UP)
udhcpc -i eth0
